### ISSUE TITLE
需要支持头部插槽自适应宽度

### ISSUE THREAD

**Issue by Too-Tao** [jd-opensource/drip-table#311]
当前头部插槽的宽度无法根据头部容器进行自适应宽度设置。
需要给插槽设置中增加如空白栏宽度的设置
<img width="950" alt="image" src="https://user-images.githubusercontent.com/40811570/206883863-355638ec-687a-459c-a60e-b028563ef2ba.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/40811570/206883868-fa57b76a-e04f-48db-9236-ca10fca36c07.png">

**Comment by Too-Tao** [comment]
> 

插槽的父级容器宽度无法设置。自定义插槽是根据父级容器宽度自适应的，父级容器宽度无法设置，自定义插槽宽度就无法设置为自适应
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/40811570/206888505-30f0f065-aa8c-42aa-8616-fc225ebef816.png">

**Comment by raoenhui** [comment]
1.issue：https://github.com/JDFED/drip-table/issues/311
2.目前行插槽只支持schema中进行配置，没有generator的能力
3.行插槽的外边距需要开放，目前有个默认的padding
![image](https://user-images.githubusercontent.com/14011130/206980230-b8e16978-d684-4075-a6ad-3742f3e7d3dd.png)

**Comment by tinymins** [comment]
3 已解決
