### ISSUE TITLE
表格自带序号功能

### ISSUE THREAD

**Issue by raoenhui** [jd-opensource/drip-table#324]
**Is your feature request related to a problem? Please describe.**
表格自带序号功能

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/14011130/207804500-f200bd17-abb4-47f9-a58b-b5f255dc3394.png)

**Comment by raoenhui** [comment]
如果一页有20个，第2页的第一行序号是21

**Comment by tinymins** [comment]
已实现，参见 https://github.com/jd-opensource/drip-table/issues/396
