### ISSUE TITLE
文本组件解析value数组的形式

### ISSUE THREAD

**Issue by abmxb789** [jd-opensource/drip-table#338]
**Is your feature request related to a problem? Please describe.**
通过表单多选框配置数据的时候，接口返回[value]形式的时候，希望可以解析成对应的label拼接，目前只支持单个字符串解析

**Describe the solution you'd like**
文本组件通过配置映射关系的形式，可以自动解析出来

**Describe alternatives you've considered**
通过获取当前列的column，在自定义文本来去格式化数据

**Additional context**

**Comment by raoenhui** [comment]
https://drip-table.jd.com/drip-table/components/text#i18n

**Comment by raoenhui** [comment]
{
      key: "mock_1",
      title: "商品名称",
      dataIndex: "status",
      component: "text",
      options: {
        mode: "single",
        i18n: {
          onSale: "售卖中"
        }
      },
    },value为['onSale','finish'],想转成“售卖中，完成”

**Comment by helloqian12138** [comment]
通过字段数据处理即可
