### ISSUE TITLE
表格表头不滑动的问题

### ISSUE THREAD

**Issue by helloqian12138** [jd-opensource/drip-table#382]
**Describe the bug**
表格头部不滚动，表格主体滚动
由于用户只提供了一张图，暂时无法复现

**To Reproduce**
<img width="758" alt="image" src="https://github.com/JDFED/drip-table/assets/13211910/a03e08b6-6103-40b9-a375-51415883a1e4">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Drip-table version:
 - Drip-table-generator version (optional):
 - React version:

**Smartphone (please complete the following information):**
 - Drip-table version:
 - Drip-table-generator version (optional):
 - React version:

**Additional context**

**Comment by tinymins** [comment]
最新版已修复
