### ISSUE TITLE
文本组件Tooltip配置常用属性

### ISSUE THREAD

**Issue by helloqian12138** [jd-opensource/drip-table#395]
**Is your feature request related to a problem? Please describe.**
目前文本组件的Tooltip无法配置更多的属性，如果遇到很长的链接就显得非常长，希望可以把常用属性放开可以配置
比如：Tooltip triiger、placement、width
另外也支持自定义Tooltip中的内容

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tinymins** [comment]
已支持，更新到最新即可
