### ISSUE TITLE
新增序号组件

### ISSUE THREAD

**Issue by helloqian12138** [jd-opensource/drip-table#396]
**Is your feature request related to a problem? Please describe.**
希望可以支持序号的组件，序号不随数据排序变化而变化，能够设置样式、格式[1、一、No. 1]
每页固定如下：
第一页: 【1,2，。。。，pageSize】
第二页：【pageSize + 1，。。。，2*pageSize】
最后一页：【pageSize（pages - 1）+1，。。。，total】

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tinymins** [comment]
已实现，使用文本组件模版字符串即可
