### ISSUE TITLE
新增图标组件

### ISSUE THREAD

**Issue by helloqian12138** [jd-opensource/drip-table#397]
**Is your feature request related to a problem? Please describe.**
添加图标组件：
允许用户能够选取常用图标 或者 输入 svg 字符串 或者输入 链接 的形式进行渲染
允许用户配置样式：颜色，大小
允许用户根据 dataSource 来判断展示不同的图标或者不同样式

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tinymins** [comment]
已完成
